### ISSUE TITLE
[Feature] Use Kyverno's image verifier to interact with the plugin

### ISSUE THREAD

**Issue by vishal-chdhry** [nirmata/kyverno-notation-aws#45]
## Description 

We are planning to add support for updating `kyverno.io/verify-images` which enforces that all images allowed in a cluster are signed. Currently that annotation is protected and can only be updated by kyverno. To make this work we will have to make that annotation accessible by everyone which is a security issue.

Moreover, that annotation is an internal implementation detail of kyverno, so if kyverno decides to remove that extension in the future it will require us to update the plugin as well.

## Proposed Solution

Add a new type of Image verification called `ExternalService` Which will take a URL as an input,
```yaml
verifyImages:
  - type: ExternalService
    url: "https://svc.kyverno-notation-aws/checkimages?trustPolicy={{request.namespace}}"
    imageReferences:
      - "844333597536.dkr.ecr.us-west-2.amazonaws.com/*"
    attestations:
      - type: sbom/cyclone-dx
        conditions:
            all:
            - key: "{{creationInfo.licenseListVersion}}"
              operator: Equals
              value: "3.17"
              message: invalid license version
```
The URL will receive requests from kyverno and kyverno will pass/fail the policy based on output from the URL.

## Unresolved Questions

1. Should all the image for a resource be send in one trip?
    **PROS**
    1. There will only be one trip so network latency will be much better.

    **CONS** 
    1. If we want to verify the conditions in kyverno and not in the plugin. Response payload can have a lot of SBOMs/VulnScan reports. In case of 1 image per trip. Payload size will be much smaller.

2. Should the conditions be verified in the plugin?
    **PROS**
    1. The response object will only contain a bool stating verification status and mutated digests, instead of having attestation payload.

    **CONS** 
    1. Makes creating a new plugin complex
