### ISSUE TITLE
Can't apply kyverno policy

### ISSUE THREAD

**Issue by mihirgosai5** [nirmata/kyverno-notation-aws#54]
I'm encountering an issue when trying to deploy a plugin on an EKS cluster using Helm. The policy provided within the samples folder seems to be incompatible with the chart deployment. When I attempt to apply the policy with kubectl apply -f kyverno-policy.yaml, I receive the following error:
```
Error from server: error when creating "../kyvernov2/templates/kyverno-policy.yaml": admission webhook "validate-policy.kyverno.svc" denied the request: policy contains invalid variables: variable substitution failed for rule call-aws-signer-extension: variable images must match regex "request\.|element|elementIndex|@|images\.|image\.|([a-z_0-9]+\()[^{}]" or patterns [tlscerts* response*]
```
**Current Configuration:**

The plugin is deployed via [kyverno-notation-aws Helm Chart](https://github.com/nirmata/kyverno-notation-aws/tree/main/charts/kyverno-notation-aws).
Kyverno is deployed through the [kyverno Helm Chart](https://github.com/kyverno/kyverno/tree/main/charts/kyverno).

**Policy Configuration:**
The policy I am applying is the kyverno-policy.yaml provided in the samples folder:
```
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-images     
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  webhookTimeoutSeconds: 30
  schemaValidation: false
  rules:
  - name: call-aws-signer-extension
    match:
      any:
      - resources:
          namespaces:
          - test-notation
          kinds:
          - Pod
          operations:
            - CREATE
            - UPDATE
    context:
    - name: tlscerts
      apiCall:
        urlPath: "/api/v1/namespaces/kyverno-notation-aws/secrets/svc.kyverno-notation-aws.svc.tls-pair"
        jmesPath: "base64_decode( data.\"tls.crt\" )"
    - name: response
      apiCall:
        method: POST
        data:
        - key: images
          value: "{{images}}"
        - key: trustPolicy
          value: "tp-{{request.namespace}}"
        - key: attestations
          value: 
          - imageReference: "*"
            type: 
            - name: sbom/example
              conditions:
                all:
                - key: \{{creationInfo.licenseListVersion}}
                  operator: Equals
                  value: "3.17"
                  message: invalid license version
        service:
          url: https://svc.kyverno-notation-aws/checkimages
          caBundle: '{{ tlscerts }}'
    mutate:
      foreach:
      - list: "response.results"
        patchesJson6902: |-
            - path: {{ element.path }}
              op: replace
              value: {{ element.image }}
```
**Additional Information:**

The policy deployment works without a problem when I deploy both kyverno and the plugin manually, following the instructions provided [here](https://github.com/nirmata/kyverno-notation-aws/tree/main#install).
However, it fails when both are deployed via Helm. Is this a version issue or an issue with the policy?
