### ISSUE TITLE
Cluster Policy Does Not Call call-aws-signer-extension if Results are Not Used in Mutate

### ISSUE THREAD

**Issue by b-eisen** [nirmata/kyverno-notation-aws#58]
The cluster policy does not call the `call-aws-signer-extension` if the results object is not used in the mutate block.

Scenario: 
Due to #57 I attempted to change the mutate block to not change the images due to the digests not being present in the results object.  When I changed to a mutate action that does not use the results object the aws-signer-notation service (controller) is never called.  (This is safe for my purposes due to the fact that the digests were provided in the original intercepted Pod creation. I had to workaround this by defining another mutate action that iterated through the results object,  but did not replace with any unacceptable values.

Does not invoke the extension:

```
    mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              org.dev/annotation: "true"
```

Invokes the extension:
```
    mutate:
      foreach:
      - list: "response.results"
        patchStrategicMerge:
          metadata:
            annotations:
              org.dev/annotation: "true"
```
