### ISSUE TITLE
HTTP 406 Not Acceptable: Token is not authorized error after successful policy check.

### ISSUE THREAD

**Issue by hmalayap** [nirmata/kyverno-notation-aws#64]
Our image signature policy check using Kyverno aws notation plugin works with the following policy but the admissions policy report changes from Pass to Error with in a few minutes with the following error:

```
    message: failed to check deny conditions: failed to substitute variables in condition key: 
    failed to resolve response.verified at path : failed to fetch data for APICall: 
    HTTP 406 Not Acceptable: Token is not authorized
    policy: check-images
    result: error
    rule: check-image-signature-aws-signer
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1698768481

```

It appears the Pass policy report is overwritten by this error report with in 1 - 2 minutes of deployment. 

Below is our Kyverno policy mutate block:

```
 validate:
      message: "Unable to verify image signature. Please ensure image is signed by AWS Signer"
      deny:
        conditions: 
          all:
          - key: "{{ response.verified }}"
            operator: EQUALS
            value: false

```
You can replicate this issue by applying this policy and deploy a valid signed container image. Observe the policy report to see it pass at the time time of deployment and then error out in subsequent report runs. 

<img width="1049" alt="image" src="https://github.com/nirmata/kyverno-notation-aws/assets/112533809/7422c654-b3cb-4aa4-a89f-5869207b3cff">

[secpolicy(1).txt](https://github.com/nirmata/kyverno-notation-aws/files/13219484/secpolicy.1.txt)
